name: "My First Example Workflow"

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps: 
        - name: Welcome Message
          run: echo "This is my forst workflow"

        - name: List Files
          run: ls
        
        - name: Read Readme file
          run: cat README.md