name: "My First Example Workflow"

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps: 
        - name: "checkout repo"
          uses: actions/checkout@v5
        - name: Welcome Message
          run: echo "This is my forst workflow"

        - name: Get the current directory
          run: pwd

        - name: List Files
          run: ls
        
        - name: Read Readme file
          run: cat README.md